/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.project_tubes_hikerbest.view;

/**
 *
 * @author V16_E
 */
import com.mycompany.project_tubes_hikerbest.controller.BookingController;
import com.mycompany.project_tubes_hikerbest.controller.GunungController;
import com.mycompany.project_tubes_hikerbest.model.Booking;
import com.mycompany.project_tubes_hikerbest.model.Gunung;
import java.util.List;

public class BookingPanel extends javax.swing.JPanel {

    private BookingController bookingController = new BookingController();
    private GunungController gunungController = new GunungController();

    public BookingPanel() {
        initComponents();
        loadGunung();
    }

    private void loadGunung() {
        cmbGunung.removeAllItems();
        cmbGunung.addItem("Pilih Gunung (Lokasi)");
        List<Gunung> list = gunungController.getAllGunung();
        for (Gunung g : list) {
            cmbGunung.addItem(g.getNama() + " (" + g.getLokasi() + ")");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbGunung = new javax.swing.JComboBox<>();
        lblJudul = new javax.swing.JLabel();
        lblGunung = new javax.swing.JLabel();
        lblTanggal = new javax.swing.JLabel();
        lblJumlah = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        txtTanggal = new javax.swing.JTextField();
        lblNama = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();

        cmbGunung.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Gunung (Lokasi)", "Gunung Bangkok (Purwakarta)", "Gunung Burangrang (Bandung Barat)", "Gunung Cikuray (Garut)", "Gunung Ciremai (Kuningan)", "Gunung Galanggung (Tasikmalaya)", "Gunung Gede (Sukabumi)", "Gunung Malabar (Bandung)", "Gunung Manglayang (Sumedang)", "Gunung Papandayan (garut)", "Gunung Puntang (Bandung)", "Gunung Putri (Bandung Barat)", "Gunung Salak (Bogor)" }));

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblJudul.setText("    FORM BOOKING PENDAKIAN       ");

        lblGunung.setText("Nama Gunung");

        lblTanggal.setText("Tanggal Naik");

        lblJumlah.setText("Jumlah Pendaki");

        lblNama.setText("Nama");

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJudul)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblGunung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblJumlah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblNama, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBatal))
                            .addComponent(txtTanggal)
                            .addComponent(txtJumlah)
                            .addComponent(cmbGunung, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNama))))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNama, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGunung)
                    .addComponent(cmbGunung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTanggal)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJumlah)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBatal)
                    .addComponent(btnSimpan))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String nama = txtNama.getText().trim();
        String gunungPilihan = (String) cmbGunung.getSelectedItem();
        String tanggal = txtTanggal.getText().trim();
        String jumlah = txtJumlah.getText().trim();

        if (nama.isEmpty() || gunungPilihan.equals("Pilih Gunung (Lokasi)") || tanggal.isEmpty() || jumlah.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String namaGunung = gunungPilihan.split(" \\(")[0];

        Booking b = new Booking();
        b.setNamaPendaki(nama);
        b.setNamaGunung(namaGunung);
        b.setTanggalNaik(tanggal);
        b.setJumlahOrang(Integer.parseInt(jumlah));
        b.setTotalHarga(0);
        b.setStatus("Menunggu");
        b.setCatatan("");

        if (bookingController.tambahBooking(b)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Booking berhasil disimpan!");
            btnBatalActionPerformed(evt);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan booking!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        txtNama.setText("");
        txtTanggal.setText("");
        txtJumlah.setText("");
        cmbGunung.setSelectedIndex(0);
    }//GEN-LAST:event_btnBatalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbGunung;
    private javax.swing.JLabel lblGunung;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}
