/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.project_tubes_hikerbest.view;

/**
 *
 * @author V16_E
 */
import com.mycompany.project_tubes_hikerbest.controller.BookingController;
import com.mycompany.project_tubes_hikerbest.controller.GunungController;
import com.mycompany.project_tubes_hikerbest.model.Booking;
import java.util.List;

public class DashboardPanel extends javax.swing.JPanel {

    private GunungController gunungController = new GunungController();
    private BookingController bookingController = new BookingController();

    public DashboardPanel() {
        initComponents();
        loadDataFromDB();
    }

    private void loadDataFromDB() {
        // Card statistik
        lblTotalGunung.setText(String.valueOf(gunungController.getTotalGunung()));
        lblTotalBooking.setText(String.valueOf(bookingController.getTotalBooking()));
        lblTotalPending.setText(String.valueOf(bookingController.getTotalPending()));

        // Tabel booking saya
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
            new String[]{"No", "Nama Pendaki", "Gunung", "Tanggal Naik", "Jumlah", "Status"}, 0
        );
        tabelBooking.setModel(model);

        List<Booking> list = bookingController.getBookingTerbaru(10);
        int no = 1;
        for (Booking b : list) {
            model.addRow(new Object[]{
                no++,
                b.getNamaPendaki(),
                b.getNamaGunung(),
                b.getTanggalNaik(),
                b.getJumlahOrang(),
                b.getStatus()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        cardGunung = new javax.swing.JPanel();
        lblKeteranganGunung = new javax.swing.JLabel();
        lblTotalGunung = new javax.swing.JLabel();
        cardBooking = new javax.swing.JPanel();
        lblKeteranganBooking = new javax.swing.JLabel();
        lblTotalBooking = new javax.swing.JLabel();
        cardPending = new javax.swing.JPanel();
        lblKeteranganPending = new javax.swing.JLabel();
        lblTotalPending = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBooking = new javax.swing.JTable();
        lblBookingSaya = new javax.swing.JLabel();

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblJudul.setText("Selamat Datang di HikerBest");

        cardGunung.setBackground(new java.awt.Color(255, 255, 255));

        lblKeteranganGunung.setText("Total Gunung");

        lblTotalGunung.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalGunung.setText("12");

        javax.swing.GroupLayout cardGunungLayout = new javax.swing.GroupLayout(cardGunung);
        cardGunung.setLayout(cardGunungLayout);
        cardGunungLayout.setHorizontalGroup(
            cardGunungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardGunungLayout.createSequentialGroup()
                .addGroup(cardGunungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardGunungLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblKeteranganGunung))
                    .addGroup(cardGunungLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblTotalGunung)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        cardGunungLayout.setVerticalGroup(
            cardGunungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardGunungLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(lblTotalGunung, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblKeteranganGunung)
                .addGap(22, 22, 22))
        );

        cardBooking.setBackground(new java.awt.Color(255, 255, 255));

        lblKeteranganBooking.setText("Total Booking");

        lblTotalBooking.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalBooking.setText("0");

        javax.swing.GroupLayout cardBookingLayout = new javax.swing.GroupLayout(cardBooking);
        cardBooking.setLayout(cardBookingLayout);
        cardBookingLayout.setHorizontalGroup(
            cardBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardBookingLayout.createSequentialGroup()
                .addGroup(cardBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardBookingLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblKeteranganBooking))
                    .addGroup(cardBookingLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblTotalBooking)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        cardBookingLayout.setVerticalGroup(
            cardBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardBookingLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(lblTotalBooking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblKeteranganBooking)
                .addGap(21, 21, 21))
        );

        cardPending.setBackground(new java.awt.Color(255, 255, 255));

        lblKeteranganPending.setText("Pending");

        lblTotalPending.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalPending.setText("0");

        javax.swing.GroupLayout cardPendingLayout = new javax.swing.GroupLayout(cardPending);
        cardPending.setLayout(cardPendingLayout);
        cardPendingLayout.setHorizontalGroup(
            cardPendingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPendingLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(cardPendingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKeteranganPending)
                    .addGroup(cardPendingLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblTotalPending)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        cardPendingLayout.setVerticalGroup(
            cardPendingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardPendingLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(lblTotalPending)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblKeteranganPending)
                .addGap(23, 23, 23))
        );

        tabelBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelBooking);

        lblBookingSaya.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBookingSaya.setText("Booking saya");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblJudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cardGunung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cardPending, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cardBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 57, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblBookingSaya)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblJudul)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cardBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cardGunung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cardPending, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(lblBookingSaya)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardBooking;
    private javax.swing.JPanel cardGunung;
    private javax.swing.JPanel cardPending;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBookingSaya;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblKeteranganBooking;
    private javax.swing.JLabel lblKeteranganGunung;
    private javax.swing.JLabel lblKeteranganPending;
    private javax.swing.JLabel lblTotalBooking;
    private javax.swing.JLabel lblTotalGunung;
    private javax.swing.JLabel lblTotalPending;
    private javax.swing.JTable tabelBooking;
    // End of variables declaration//GEN-END:variables
}
