/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.project_tubes_hikerbest.view;

/**
 *
 * @author V16_E
 */
import com.mycompany.project_tubes_hikerbest.controller.BookingController;
import com.mycompany.project_tubes_hikerbest.controller.GunungController;
import com.mycompany.project_tubes_hikerbest.model.Booking;
import java.util.List;

public class DashboardPanel extends javax.swing.JPanel {

    private GunungController gunungController = new GunungController();
    private BookingController bookingController = new BookingController();
    private int selectedBookingId = -1;
    private String selectedStatus = "";

    public DashboardPanel() {
        initComponents();
        loadDataFromDB();
    }

    private void loadDataFromDB() {
        com.mycompany.project_tubes_hikerbest.model.User u =
            com.mycompany.project_tubes_hikerbest.util.Session.getCurrentUser();
        String namaPendaki = (u != null) ? u.getNama() : "";

        lblTotalGunung.setText(String.valueOf(gunungController.getTotalGunung()));

        List<Booking> list = bookingController.getBookingByNamaPendaki(namaPendaki);

        lblTotalBooking.setText(String.valueOf(list.size()));
        long totalPending = list.stream().filter(b -> "Menunggu".equalsIgnoreCase(b.getStatus())).count();
        lblTotalPending.setText(String.valueOf(totalPending));

        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
            new String[]{"No", "Nama Pendaki", "Gunung", "Tanggal Naik", "Jumlah", "Status"}, 0
        );
        tabelBooking.setModel(model);

        int no = 1;
        for (Booking b : list) {
            model.addRow(new Object[]{
                no++,
                b.getNamaPendaki(),
                b.getNamaGunung(),
                b.getTanggalNaik(),
                b.getJumlahOrang(),
                b.getStatus()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        cardGunung = new javax.swing.JPanel();
        lblKeteranganGunung = new javax.swing.JLabel();
        lblTotalGunung = new javax.swing.JLabel();
        cardBooking = new javax.swing.JPanel();
        lblKeteranganBooking = new javax.swing.JLabel();
        lblTotalBooking = new javax.swing.JLabel();
        cardPending = new javax.swing.JPanel();
        lblKeteranganPending = new javax.swing.JLabel();
        lblTotalPending = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBooking = new javax.swing.JTable();
        lblBookingSaya = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblJudul.setText("Selamat Datang di HikerBest");

        cardGunung.setBackground(new java.awt.Color(255, 255, 255));

        lblKeteranganGunung.setText("Total Gunung");

        lblTotalGunung.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalGunung.setText("12");

        javax.swing.GroupLayout cardGunungLayout = new javax.swing.GroupLayout(cardGunung);
        cardGunung.setLayout(cardGunungLayout);
        cardGunungLayout.setHorizontalGroup(
            cardGunungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardGunungLayout.createSequentialGroup()
                .addGroup(cardGunungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardGunungLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblKeteranganGunung))
                    .addGroup(cardGunungLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblTotalGunung)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        cardGunungLayout.setVerticalGroup(
            cardGunungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardGunungLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(lblTotalGunung, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblKeteranganGunung)
                .addGap(22, 22, 22))
        );

        cardBooking.setBackground(new java.awt.Color(255, 255, 255));

        lblKeteranganBooking.setText("Total Booking");

        lblTotalBooking.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalBooking.setText("0");

        javax.swing.GroupLayout cardBookingLayout = new javax.swing.GroupLayout(cardBooking);
        cardBooking.setLayout(cardBookingLayout);
        cardBookingLayout.setHorizontalGroup(
            cardBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardBookingLayout.createSequentialGroup()
                .addGroup(cardBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardBookingLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblKeteranganBooking))
                    .addGroup(cardBookingLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblTotalBooking)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        cardBookingLayout.setVerticalGroup(
            cardBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardBookingLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(lblTotalBooking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblKeteranganBooking)
                .addGap(21, 21, 21))
        );

        cardPending.setBackground(new java.awt.Color(255, 255, 255));

        lblKeteranganPending.setText("Pending");

        lblTotalPending.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalPending.setText("0");

        javax.swing.GroupLayout cardPendingLayout = new javax.swing.GroupLayout(cardPending);
        cardPending.setLayout(cardPendingLayout);
        cardPendingLayout.setHorizontalGroup(
            cardPendingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPendingLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(cardPendingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKeteranganPending)
                    .addGroup(cardPendingLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblTotalPending)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        cardPendingLayout.setVerticalGroup(
            cardPendingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardPendingLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(lblTotalPending)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblKeteranganPending)
                .addGap(23, 23, 23))
        );

        tabelBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBookingMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelBooking);

        lblBookingSaya.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBookingSaya.setText("Booking saya");

        btnUpdate.setText("Update Booking");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus Booking");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblJudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cardGunung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cardPending, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cardBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblBookingSaya)
                                .addGap(54, 54, 54)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 57, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblJudul)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cardBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cardGunung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cardPending, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBookingSaya)
                    .addComponent(btnUpdate)
                    .addComponent(btnHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (selectedBookingId == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih booking dari tabel dulu!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!selectedStatus.equals("Menunggu")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Hanya booking dengan status 'Menunggu' yang bisa diupdate!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // ambil data booking yang dipilih
        Booking b = bookingController.getBookingById(selectedBookingId);
        if (b == null) return;

        // dialog input update
        javax.swing.JTextField txtTanggal = new javax.swing.JTextField(b.getTanggalNaik());
        javax.swing.JTextField txtJumlah = new javax.swing.JTextField(String.valueOf(b.getJumlahOrang()));

        Object[] fields = {
            "Tanggal Naik:", txtTanggal,
            "Jumlah Orang:", txtJumlah
        };

        int result = javax.swing.JOptionPane.showConfirmDialog(this, fields, "Update Booking", javax.swing.JOptionPane.OK_CANCEL_OPTION);
        if (result != javax.swing.JOptionPane.OK_OPTION) return;

        b.setTanggalNaik(txtTanggal.getText().trim());
        b.setJumlahOrang(Integer.parseInt(txtJumlah.getText().trim()));

        if (bookingController.updateBooking(b)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Booking berhasil diupdate!");
            selectedBookingId = -1;
            selectedStatus = "";
            loadDataFromDB();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal mengupdate booking!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        if (selectedBookingId == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih booking dari tabel dulu!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
        }
        if (!selectedStatus.equals("Menunggu")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Hanya booking dengan status 'Menunggu' yang bisa dihapus!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin batalkan booking ini?", "Konfirmasi", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm != javax.swing.JOptionPane.YES_OPTION) return;

        if (bookingController.hapusBooking(selectedBookingId)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Booking berhasil dibatalkan!");
            selectedBookingId = -1;
            selectedStatus = "";
            loadDataFromDB();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal membatalkan booking!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tabelBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBookingMouseClicked
        int row = tabelBooking.getSelectedRow();
        if (row == -1) return;

        com.mycompany.project_tubes_hikerbest.model.User u =
            com.mycompany.project_tubes_hikerbest.util.Session.getCurrentUser();
        String namaPendaki = (u != null) ? u.getNama() : "";

        List<Booking> list = bookingController.getBookingByNamaPendaki(namaPendaki);
        if (row < list.size()) {
            selectedBookingId = list.get(row).getId();
            selectedStatus = list.get(row).getStatus();
        }
    }//GEN-LAST:event_tabelBookingMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel cardBooking;
    private javax.swing.JPanel cardGunung;
    private javax.swing.JPanel cardPending;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBookingSaya;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblKeteranganBooking;
    private javax.swing.JLabel lblKeteranganGunung;
    private javax.swing.JLabel lblKeteranganPending;
    private javax.swing.JLabel lblTotalBooking;
    private javax.swing.JLabel lblTotalGunung;
    private javax.swing.JLabel lblTotalPending;
    private javax.swing.JTable tabelBooking;
    // End of variables declaration//GEN-END:variables
}
