/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.project_tubes_hikerbest.view;

/**
 *
 * @author V16_E
 */
public class DashboardAdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form DashboardAdminPanel
     */
    public DashboardAdminPanel() {
    initComponents();
    loadDataFromDB();
    }

    private void loadDataFromDB() {
        try {
            java.sql.Connection conn = com.mycompany.project_tubes_hikerbest.database.DatabaseConnection.getConnection();

            // Total Gunung
            java.sql.ResultSet rs1 = conn.createStatement().executeQuery("SELECT COUNT(*) as total FROM gunung");
            if (rs1.next()) lblTotalGunung.setText(String.valueOf(rs1.getInt("total")));

            // Total User
            java.sql.ResultSet rs2 = conn.createStatement().executeQuery("SELECT COUNT(*) as total FROM users");
            if (rs2.next()) lblTotalUser.setText(String.valueOf(rs2.getInt("total")));

            // Total Booking
            java.sql.ResultSet rs3 = conn.createStatement().executeQuery("SELECT COUNT(*) as total FROM booking");
            if (rs3.next()) lblTotalBooking.setText(String.valueOf(rs3.getInt("total")));

            // Tabel Booking Terbaru
            javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
                new String[]{"No", "Nama", "Gunung", "Tanggal Naik", "Jumlah Pendaki", "Status"}, 0
            );
            tabelBooking.setModel(model);
            java.sql.ResultSet rs4 = conn.createStatement().executeQuery(
                "SELECT id, nama_pendaki, nama_gunung, tanggal_naik, jumlah_orang, status FROM booking ORDER BY id DESC LIMIT 10"
            );
            int no = 1;
            while (rs4.next()) {
                model.addRow(new Object[]{
                    no++,
                    rs4.getString("nama_pendaki"),
                    rs4.getString("nama_gunung"),
                    rs4.getString("tanggal_naik"),
                    rs4.getInt("jumlah_orang"),
                    rs4.getString("status")
                });
            }

        } catch (java.sql.SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardUser = new javax.swing.JPanel();
        lblTotalUser = new javax.swing.JLabel();
        lblKetUser = new javax.swing.JLabel();
        lblJudul = new javax.swing.JLabel();
        cardBooking = new javax.swing.JPanel();
        lblTotalBooking = new javax.swing.JLabel();
        lblKetBooking = new javax.swing.JLabel();
        cardGunung = new javax.swing.JPanel();
        lblTotalGunung = new javax.swing.JLabel();
        lblKetGunung = new javax.swing.JLabel();
        scrollBooking = new javax.swing.JScrollPane();
        tabelBooking = new javax.swing.JTable();
        lblRiwayat = new javax.swing.JLabel();

        cardUser.setBackground(new java.awt.Color(255, 255, 255));

        lblTotalUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotalUser.setText("0");

        lblKetUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblKetUser.setText("Total User");

        javax.swing.GroupLayout cardUserLayout = new javax.swing.GroupLayout(cardUser);
        cardUser.setLayout(cardUserLayout);
        cardUserLayout.setHorizontalGroup(
            cardUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardUserLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(lblKetUser)
                .addGap(16, 16, 16))
            .addGroup(cardUserLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblTotalUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardUserLayout.setVerticalGroup(
            cardUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardUserLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTotalUser)
                .addGap(18, 18, 18)
                .addComponent(lblKetUser)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblJudul.setText("Dashboard Admin  ");

        cardBooking.setBackground(new java.awt.Color(255, 255, 255));

        lblTotalBooking.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotalBooking.setText("0");

        lblKetBooking.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblKetBooking.setText("Total Booking");

        javax.swing.GroupLayout cardBookingLayout = new javax.swing.GroupLayout(cardBooking);
        cardBooking.setLayout(cardBookingLayout);
        cardBookingLayout.setHorizontalGroup(
            cardBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardBookingLayout.createSequentialGroup()
                .addGroup(cardBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardBookingLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblKetBooking))
                    .addGroup(cardBookingLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblTotalBooking)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardBookingLayout.setVerticalGroup(
            cardBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardBookingLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTotalBooking)
                .addGap(18, 18, 18)
                .addComponent(lblKetBooking)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardGunung.setBackground(new java.awt.Color(255, 255, 255));

        lblTotalGunung.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotalGunung.setText("12");

        lblKetGunung.setText("Total Gunung");

        javax.swing.GroupLayout cardGunungLayout = new javax.swing.GroupLayout(cardGunung);
        cardGunung.setLayout(cardGunungLayout);
        cardGunungLayout.setHorizontalGroup(
            cardGunungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardGunungLayout.createSequentialGroup()
                .addGroup(cardGunungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardGunungLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblTotalGunung))
                    .addGroup(cardGunungLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblKetGunung)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        cardGunungLayout.setVerticalGroup(
            cardGunungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardGunungLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTotalGunung)
                .addGap(18, 18, 18)
                .addComponent(lblKetGunung)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scrollBooking.setBackground(new java.awt.Color(255, 255, 255));

        tabelBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama", "Gunung", "Tanggal Naik", "Jumlah Pendaki", "Status"
            }
        ));
        scrollBooking.setViewportView(tabelBooking);

        lblRiwayat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRiwayat.setText("Booking Terbaru");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cardUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cardBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cardGunung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblJudul)
                        .addGap(152, 152, 152))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblRiwayat)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scrollBooking, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudul)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cardUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardGunung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardBooking, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lblRiwayat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardBooking;
    private javax.swing.JPanel cardGunung;
    private javax.swing.JPanel cardUser;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblKetBooking;
    private javax.swing.JLabel lblKetGunung;
    private javax.swing.JLabel lblKetUser;
    private javax.swing.JLabel lblRiwayat;
    private javax.swing.JLabel lblTotalBooking;
    private javax.swing.JLabel lblTotalGunung;
    private javax.swing.JLabel lblTotalUser;
    private javax.swing.JScrollPane scrollBooking;
    private javax.swing.JTable tabelBooking;
    // End of variables declaration//GEN-END:variables
}
