/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.project_tubes_hikerbest.view;

/**
 *
 * @author V16_E
 */
import com.mycompany.project_tubes_hikerbest.controller.GunungController;
import com.mycompany.project_tubes_hikerbest.model.Gunung;
import java.util.List;

public class GunungManagementPanel extends javax.swing.JPanel {

    private GunungController gunungController = new GunungController();
    private int selectedGunungId = -1;
    
    public GunungManagementPanel() {
        initComponents();
        loadDataGunung();
    }
    private void loadDataGunung() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
            new String[]{"No", "Nama", "Lokasi", "Ketinggian", "Harga", "Status"}, 0
        );
        tabelGunung.setModel(model);

        List<Gunung> list = gunungController.getAllGunung();
        int no = 1;
        for (Gunung g : list) {
            model.addRow(new Object[]{
                no++,
                g.getNama(),
                g.getLokasi(),
                g.getKetinggian() + " mdpl",
                "Rp " + g.getHarga(),
                g.getStatus()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelGunung = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Deskripsi = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtKetinggian = new javax.swing.JTextField();
        txtDeskripsi = new javax.swing.JTextField();
        txtLokasi = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("  Manajemen Gunung     ");

        tabelGunung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama", "Lokasi", "Ketinggian", "Harga", "Deskripsi"
            }
        ));
        tabelGunung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelGunungMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelGunung);

        jLabel2.setText("Nama:");

        jLabel3.setText("Ketinggian:");

        Deskripsi.setText("Deskripsi:");

        jLabel5.setText("Lokasi:");

        jLabel6.setText("Harga:");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(Deskripsi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                    .addComponent(txtKetinggian))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHarga)
                                    .addComponent(txtLokasi)))
                            .addComponent(txtDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(52, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnSimpan)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addGap(18, 18, 18)
                .addComponent(btnHapus)
                .addGap(18, 18, 18)
                .addComponent(btnBatal)
                .addGap(0, 31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(txtKetinggian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Deskripsi)
                    .addComponent(txtDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnUpdate)
                    .addComponent(btnHapus)
                    .addComponent(btnBatal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String nama = txtNama.getText().trim();
        String lokasi = txtLokasi.getText().trim();
        String ketinggian = txtKetinggian.getText().trim();
        String harga = txtHarga.getText().trim();
        String deskripsi = txtDeskripsi.getText().trim();

        if (nama.isEmpty() || lokasi.isEmpty() || ketinggian.isEmpty() || harga.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nama, Lokasi, Ketinggian, dan Harga wajib diisi!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        Gunung g = new Gunung();
        g.setNama(nama);
        g.setLokasi(lokasi);
        g.setKetinggian(Integer.parseInt(ketinggian));
        g.setHarga(Double.parseDouble(harga));
        g.setDeskripsi(deskripsi);
        g.setStatus("Aktif");

        if (gunungController.tambahGunung(g)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gunung berhasil ditambahkan!");
            btnBatalActionPerformed(evt);
            loadDataGunung();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal menambahkan gunung!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (selectedGunungId == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih gunung dari tabel dulu!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        Gunung g = new Gunung();
        g.setId(selectedGunungId);
        g.setNama(txtNama.getText().trim());
        g.setLokasi(txtLokasi.getText().trim());
        g.setKetinggian(Integer.parseInt(txtKetinggian.getText().trim()));
        g.setHarga(Double.parseDouble(txtHarga.getText().trim()));
        g.setDeskripsi(txtDeskripsi.getText().trim());

        if (gunungController.updateGunung(g)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gunung berhasil diupdate!");
            btnBatalActionPerformed(evt);
            loadDataGunung();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal mengupdate gunung!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        if (selectedGunungId == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih gunung dari tabel dulu!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin hapus gunung ini?", "Konfirmasi", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm != javax.swing.JOptionPane.YES_OPTION) return;

        if (gunungController.hapusGunung(selectedGunungId)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gunung berhasil dihapus!");
            btnBatalActionPerformed(evt);
            loadDataGunung();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus gunung!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        txtNama.setText("");
        txtLokasi.setText("");
        txtKetinggian.setText("");
        txtHarga.setText("");
        txtDeskripsi.setText("");
        selectedGunungId = -1;
        tabelGunung.clearSelection();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void tabelGunungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelGunungMouseClicked
        int row = tabelGunung.getSelectedRow();
        if (row == -1) return;

        String namaGunung = tabelGunung.getValueAt(row, 1).toString();
        Gunung g = gunungController.getGunungByNama(namaGunung);
        if (g != null) {
            selectedGunungId = g.getId();
            txtNama.setText(g.getNama());
            txtLokasi.setText(g.getLokasi());
            txtKetinggian.setText(String.valueOf(g.getKetinggian()));
            txtHarga.setText(String.valueOf(g.getHarga()));
            txtDeskripsi.setText(g.getDeskripsi());
        }
    }//GEN-LAST:event_tabelGunungMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Deskripsi;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelGunung;
    private javax.swing.JTextField txtDeskripsi;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtKetinggian;
    private javax.swing.JTextField txtLokasi;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
